### ISSUE TITLE
Wiki: Fatal exception of type MWException

### ISSUE THREAD

**Issue by GamesOpenSource** [red-eclipse/hq-www#1]
https://redeclipse.net/wiki/How_to_Contribute_to_Red_Eclipse

[dc5f7191] 2019-08-12 05:21:04: Fatal exception of type MWException

![image](https://user-images.githubusercontent.com/54016023/62846625-dfc61c00-bcd1-11e9-9939-5298d360b6a6.png)

**Comment by qreeves** [comment]
The old wiki has been superseded by the [Website Docs](https://www.redeclipse.net/docs), but I do need to take a look at why the redirects aren't working properly. If you're looking for that page specifically, it can now be found [here](https://www.redeclipse.net/docs/Contributing).

**Comment by GamesOpenSource** [comment]
thanks, first case: https://www.redeclipse.net/contribute
![image](https://user-images.githubusercontent.com/54016023/62859262-ecac3500-bcfc-11e9-9b97-93ba850d2947.png)

**Comment by qreeves** [comment]
Fixed. Appreciate your help 😄
